config/routes.rb
Rails.application.routes.draw do
    root 'events#index'
      resources :sessions
      resources :events do
        resources :jtables
      end
end

app/models/event.rb
class Event < ActiveRecord::Base

  has_many :jtables
  has_many :sessions, through: :jtables

end

app/models/jtable.rb
class Jtable < ActiveRecord::Base

  belongs_to :event
  belongs_to :session

end

app/models/session.rb
class Session < ActiveRecord::Base

  has_many :jtables
  has_many :events, through: :jtables

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    if params[:filter] == 'tuesday'
      @events = Event.all.where(date: "12/08/2015").order('start ASC')
    elsif params[:filter] == 'wednesday'
      @events = Event.all.where(date:"12/09/2015").order('start ASC')
    else
      @events = Event.all.order('date ASC')
        if params[:filter] == 'track 1'
          @events = Event.all.where(track: "Track 1 - Pattern Recognition").order('date ASC')
        elsif params[:filter] == 'track 2'
          @events = Event.all.where(track: "Track 2 - Image, Speech, and Signal Processing").order('date ASC')
        elsif params[:filter] == 'track 3'
          @events = Event.all.where(track: "Track 3 - Document Analysis").order('date ASC')
        elsif params[:filter] == 'track 4'
          @events = Event.all.where(track: "Track 4 - Biometrics").order('date ASC')
        elsif params[:filter] == 'track 5'
          @events = Event.all.where(track: "Track 5 - Bioinformatics").order('date ASC')
        elsif params[:filter] == 'keynote'
          @events = Event.all.where(track: "Keynote").order('date ASC')
        elsif params[:filter] == 'coffee'
          @events = Event.all.where(track: "Coffee Breaks").order('date ASC')
        elsif params[:filter] == 'lunch'
          @events = Event.all.where(track: "Lunch").order('date ASC')
        elsif params[:filter] == 'party'
          @events = Event.all.where(track: "Party").order('date ASC')
        end
    end
  end





  def new
    @event = Event.new
  end

  def create
    @event = Event.new(params.require(:event).permit(:date, :start, :end, :name, :track))
    @event.save
    redirect_to events_path
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(params.require(:event).permit(:date, :start, :end, :name, :track))
    redirect_to events_path
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

end

app/controllers/jtables_controller.rb
class JtablesController < ApplicationController

  before_action do
    @event = Event.find(params[:event_id])
  end

  def index
    @jtable = Jtable.all
  end

  def new
    @jtable = @event.jtables.new
  end

  def create
    if params[:event_session] != ""
      session = Session.all.find_by_session(params[:event_session]) || Session.create(session: params[:event_session])
      Jtable.create(event_id: @event.id, session_id: session.id)
      redirect_to new_event_jtable_path, notice: 'Session was successfully created.'
    else
      redirect_to new_event_jtable_path, notice: 'Session failed to be created.'
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def index
    @sessions = Session.all
  end

  def new
    @session = Session.new
  end

  def create
    @session = Session.new(params.require(:session).permit(:session))
    @session.save
    redirect_to sessions_path
  end

  def show
    @session = Session.find(params[:id])
  end

  def edit
    @session = Session.find(params[:id])
  end

  def update
    @session = Session.find(params[:id])
    @session.update(params.require(:session).permit(:session))
    redirect_to sessions_path
  end

  def destroy
    @session = Session.find(params[:id])
    @session.destroy
    redirect_to sessions_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_form.html.erb
<%= form_for @event do |f| %>

  <%= f.label :date %>
  <%= f.date_field :date %>

  <%= f.label :start %>
  <%= f.time_field :start %>

  <%= f.label :end %>
  <%= f.time_field :end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :track %>
  <%= f.text_field :track %>

  <%= f.submit %>

<% end %>

app/views/events/index.html.erb
<h2><%= link_to "Add an Event", new_event_path %></h2>

<br>
  <%= link_to_if params[:filter], "All Days", events_path %> |
  <%= link_to_if params[:filter] != "tuesday", "Tuesday", events_path(filter:"tuesday") %> |
  <%= link_to_if params[:filter] != "wednesday", "Wednesday", events_path(filter:"wednesday") %>
<br><br>

  <%= link_to_if params[:filter], "All Events", events_path %> |
  <%= link_to_if params[:filter] != 'keynote', "Keynote", events_path(filter:"keynote") %> |
  <%= link_to_if params[:filter] != 'track 1', "Track 1", events_path(filter:"track 1") %> |
  <%= link_to_if params[:filter] != 'track 2', "Track 2", events_path(filter:"track 2") %> |
  <%= link_to_if params[:filter] != 'track 3', "Track 3", events_path(filter:"track 3") %> |
  <%= link_to_if params[:filter] != 'track 4', "Track 4", events_path(filter:"track 4") %> |
  <%= link_to_if params[:filter] != 'track 5', "Track 5", events_path(filter:"track 5") %> |
  <%= link_to_if params[:filter] != 'coffee', "Coffee Breaks", events_path(filter:"coffee") %> |
  <%= link_to_if params[:filter] != 'lunch', "Lunch", events_path(filter:"lunch") %> |
  <%= link_to_if params[:filter] != 'party', "Party", events_path(filter:"party") %>

<br><br>


<!-- <div class="row">
  <% @events.each_with_index do |event, index| %>
    <div class="col-md-3">
      <%= link_to event.track,  new_event_jtable_path(event) %>
    </div>

  <% end %>
</div> -->

<!-- <br><br><br><br><br> -->





<table class="table">
  <thead>
    <th><%= link_to "Date", events_path(:sort_param => "time") %></th><th><%= link_to "Start", events_path(:sort_param => "start") %></th><th>End</th><th>Name</th><th>Track</th>
  </thead>
  <% @events.each do |event| %>
    <tr>
      <td class="col-md-2"><%= event.date.strftime("%m/%d/%Y") %></td>
      <td class="col-md-2"><%= event.start.strftime("%I:%M %p") %></td>
      <td class="col-md-2"><%= event.end.strftime("%I:%M %p") %></td>
      <td class="col-md-3"><%= link_to event.name, event_path(event) %></td>
      <td class="col-md-3"><%= event.track %></td>
    </tr>
  <% end %>
</table>

app/views/events/new.html.erb
<br>

<%= render 'form', title: "New" %>

app/views/events/show.html.erb
<%= link_to "Home", events_path %>
<%= render 'form', title: "Edit" %>
<%= link_to "Delete", event_path(@event), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/jtables/index.html.erb
<h2><%= link_to "Add a Join Table", new_event_jtable_path %></h2>

<table class="table">
  <thead>
    <th> Join Table </th>
  </thead>
  <% @event.jtables.each do |jtable| %>
    <tr>
      <td class="col-md-2"><%= link_to jtable.session, new_event_jtable_path %></td></td>
    </tr>
  <% end %>
</table>

app/views/jtables/new.html.erb
<h2>This is a join table</h2>


<table>
  <tr>
    <th>
      <div>
        <%= @event.name %>
      </div>
      <div>

      </div>
    </th>
  </tr>

  <tr>
    <td>


      <%= form_for [@event, @jtable] do |f| %>
        <br>
        <div class="form-group col-md-offset-2">
          <%= text_field_tag :jtable %>
        </div>

        <div class="form-group">
          <%= f.submit class:"btn btn-primary col-md-offset-2" %>
        </div>

      <% end %>
    </td>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zerista</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
  <div class="container container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
  <br><br><br>
  <%= yield %>
</div>

</body>
</html>